services: 

  # client:
  #   build: ./client
  #   ports: 
  #     - 5173:5173
    
  server
  product-service:
    build: ./server/ProductService
    ports: 
      - 8080:8080
      
  # auth-service:
  #   build: ./server/AuthService
  #   ports: 
  #     - 8082:8082
  #   environment: 
  #     - ASPNETCORE_URLS=http://+:8082

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      # AMQP protocol port
      - "5672:5672"
      # Management UI port
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
     
volumes:
  database:
