services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - product-service
      - email-service
      - auth-service

  client:
    build: ./client
    
  product-service:
    build: 
      context: ./server
      dockerfile: ./ProductService/Dockerfile
    depends_on:
      rabbitmq:
         condition: service_healthy
    environment: 
      - ASPNETCORE_URLS=http://+:8080
      
  email-service:
    build: 
      context: ./server
      dockerfile: ./EmailService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment: 
      - ASPNETCORE_URLS=http://+:8086

  auth-service:
    build: 
      context: ./server
      dockerfile: ./AuthService/Dockerfile
    environment: 
      - ASPNETCORE_URLS=http://+:8082


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 11s
      retries: 5

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
     
volumes:
  database:
  rabbitmq_data:
